version: 0.2

phases:
  install:
    commands:
      - CHANGED_FILES=$(git diff --name-only HEAD HEAD~1)
      - echo "Changed files: $CHANGED_FILES"
      - if ! echo "$CHANGED_FILES" | grep -E '\.(html|css|js)$' > /dev/null; then exit 0; fi
  build:
    commands:
      - echo "No build required for a simple HTML, CSS, and JavaScript application."

  post_build:
    commands:
      - aws s3 sync . s3://webapp-auto-deploy-bucket --exclude ".git/*" --exclude "buildspec.yml" --exclude "readme.md" --delete
